name: Build

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
        with:
          platforms: all

      - name: Install Buildx
        id: buildx
        uses: docker/setup-buildx-action@master
        with:
          version: latest

      - name: Build Image and Push to GitHub Container Registry and DockerHub
        uses: docker/build-push-action@v2
        if: ${{ steps.compute-tag.outputs.result != 'FALSE' }}
        with:
          context: .
          file: ./Dockerfile
          tags: |
            jass2023/traffic-light-control:${{ steps.compute-tag.outputs.result }}
            ghcr.io/jass2023/traffic-light-control:${{ steps.compute-tag.outputs.result }}
          platforms: linux/amd64,linux/arm64/v8
          push: true
