name: Build

env:
  HARBOR_URL: harbor.mtze.me
  HARBOR_PROJECT: jass23
  IMAGE_NAME: traffic-light-control
  IMAGE_VERSION: latest

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
        with:
          platforms: all

      - name: Install Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Image and Push to GitHub Container Registry
        uses: docker/build-push-action@v2
        with:
          context: .
          tags: ghcr.io/jass2023/${{ env.IMAGE_NAME }}:${{ env.IMAGE_VERSION }}
          platforms: linux/amd64,linux/arm64/v8
          push: true

  pushHarbor:
    needs: build
    runs-on: self-hosted
    steps:
      - name: Pull Image from Github Container Registry
        run: docker pull ghcr.io/jass2023/${{ env.IMAGE_NAME }}:${{ env.IMAGE_VERSION }}

      - name: Retag Image
        run: docker tag ghcr.io/jass2023/${{ env.IMAGE_NAME }}:${{ env.IMAGE_VERSION }} ${{ env.HARBOR_URL }}/${{ env.HARBOR_PROJECT }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_VERSION }}

      - name: Login to Harbor
        uses: docker/login-action@v2
        with:
          registry: ${{ env.HARBOR_URL }}
          username: ${{ secrets.HARBOR_USER }}
          password: ${{ secrets.HARBOR_TOKEN }}

      - name: Push to Harbor
        run: docker push ${{ env.HARBOR_URL }}/${{ env.HARBOR_PROJECT }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_VERSION }}

  deploy:
    needs: pushHarbor
    runs-on: self-hosted
    steps:
      - name: Deploy
        uses: actions/checkout@v3
        with:
          fetch-depth: 1

      - name: Set Kube Config
        run: kubectl apply -f ~/.kube/config
